"""orders table

Revision ID: 5faedcdb8644
Revises: dbaef0703201
Create Date: 2025-02-10 13:16:45.392256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5faedcdb8644'
down_revision = 'dbaef0703201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_purchased', sa.Float(), nullable=False),
    sa.Column('shares_purchased', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('order_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
